flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm): # 작업을 명령하는 클래스
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])

    submit = SubmitField('Post')

flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post

main = Blueprint('main', __name__)

@main.route('/') # 기본인덱스에 대한 설정
@main.route('/home') # route는 여러개 설정해도 좋다.
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)
    # posts는 python에서 html로 보내는 변수를 의미한다.
    # posts가 아닌 다른 변수명을 활용하여 html에서 받아도 상관없다.

@main.route('/about') # 새로운 url 대한 설정
def about():
    return render_template('about.html',title='About')

flask_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required

from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        # db에는 author로 연결된 부분이 구성되어 있으므로 author라고 적어야 한다.
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html',title='New Post',
                            form=form, legend='New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) # 플라스크의 모듈로 오류 반응을 만들기 위한 함수
    
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post',post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template('create_post.html', title='Update Post',
                            form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required

from flask_blog import bcrypt, db
from flask_blog.models import User, Post
from flask_blog.users.forms import (ReigistrationForm, LoginForm, UpdateAccountForm,
                    RequestResetForm, ResetPasswordForm)
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)
# flask에서 app을 설정할 때 __name__을 입력값으로 넣었던 것과 같이 __name__을 넣어주었다.

@users.route('/register', methods=['GET','POST']) # 회원가입 url 대한 설정
# methods에서 post를 설정해야지 회원가입시 다른 페이지로 넘어갈 수 있다.
# 기본 methods는 get이다.
def register():
    if current_user.is_authenticated: # 현재 유저가 있는지 확인하는 조건문
        return redirect(url_for('main.home'))

    form = ReigistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        # 비밀번호를 bccrypt를 통해 암호화한 뒤에 데이터를 db에 저장한다.
        flash('Your account has been created! You are now able to log in','success')
        # 성공했을 경우 flash를 통해 해당 문구를 출력한다.
        return redirect(url_for('users.login')) # url_for는 함수명으로 호출하는 함수다.

    return render_template('register.html',title='Register', form=form)
    
@users.route('/login', methods=['GET','POST']) # 로그인 url 대한 설정
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') # 요청되었던 원래 페이지를 호출하는 변수
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
            # 원래 호출하려던 페이지가 있다면 그 페이지를 호출 아니라면 원래 home을 호출

        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
        # 실패했을 경우 flash를 통해 해당 문구를 출력한다.

    return render_template('login.html',title='Login', form=form)

    
@users.route('/logout') # 로그아웃 url 대한 설정
def logout():
    logout_user() # 로그아웃 해주는 함수
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET','POST'])
@login_required # 로그인이 되어 있을때만 들어갈 수 있게 막는 함수
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        
        flash('Your account has been update!', 'success')
        return redirect(url_for('users.account'))
    
    # 데이터를 새롭게 받았다면 기존의 데이터를 새로운 데이터로 변경한다.
    # 기존의 데이터는 역시나 삭제된다.
    # 이미 존재하는 데이터로 바꾸려고 한다면 이를 에러처리한다. (form에 나온다.)
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/'+current_user.image_file)
    return render_template('account.html',title='Account', 
                            image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username): # 위에서 받는 변수는 <>내부에 데이터 타입과 함께 넣고 변수는 함수에 넣어준다.
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    # first_or_404는 데이터가 존재하면 firt를 없다면 404를 실행하는 함수다.
    posts = Post.query.filter_by(author=user).\
                    order_by(Post.date_posted.desc()).\
                    paginate(page=page,per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route('/reset_password', methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is invalid or expired token', 'warnings')
        return redirect(url_for(users.reset_request))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.add(user)
        db.session.commit()
        # 비밀번호를 bccrypt를 통해 암호화한 뒤에 데이터를 db에 저장한다.
        flash('Your password has been update! You are now able to log in','success')
        # 성공했을 경우 flash를 통해 해당 문구를 출력한다.
        return redirect(url_for('users.login')) # url_for는 함수명으로 호출하는 함수다.

    return render_template('reset_token.html',title='Reset Password', form=form)

flask_blog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>
        About Page
    </h1>
{% endblock content %}

flask_blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
    <div class='content-sction'>
        <div class='media'>
            <img class='rounded-circle account-img' src="{{ image_file }}">
            <div class='media-body'>
                <h2 class='account-heading'>
                    {{ current_user.username }}
                </h2>
                <p class='text-secondary'>{{ current_user.email }}</p>
            </div>
        </div>
        <form method='POST' action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Account Info</legend>
                <div class='form-group'>
                    {{ form.username.label(class='form-control-label') }}
                    {% if form.username.errors %}
                        {{ form.username(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.email.label(class='form-control-label') }}
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.picture.label() }}
                    {{ form.picture(class='form-control-file') }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class='text-danger'>{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
    <div class='content-secion'>
        <form method='POST' action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>{{ legend }}</legend>
                <!-- form 에서 가져올 내용을 하나씩 정리하는 부분 -->
                <!-- 라벨과 forms.py의 변수명(Stringfield 내부의 스트링이 아니다.)이 모두 일치해야 한다. -->
                <!-- 불러온 데이터에 대해서 class 지정을 다음과 같이 설정해준다.-->
                <div class='form-group'>
                    {{ form.title.label(class='form-control-label') }}
                    <!-- form.username.errors에는 이미 에러에 해당하는 문구가 저장되어 있다. -->
                    <!-- 클래스명을 다음과 같이 설정하는 이유가 있다. -->
                    {% if form.title.errors %}
                        {{ form.title(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.content.label(class='form-control-label') }}
                    {% if form.content.errors %}
                        {{ form.content(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/home.html
{% extends 'layout.html' %}
<!-- 위의 내용은 layout.html에 대한 내용을 가져온다는 의미이다. -->
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class='rounded-circle article-img' src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                <!-- author의 내용을 보두 부르는 것 -> username만 부르는 것 -->
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                <!-- 현재시각 초의 소숫자리까지 출력 -> 년월일까지만 부르는 것 -->
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    <!-- 페이지 넘버를 부여하는 html 코드 -->
    {% endfor %}
    <!-- 아래 내용은 가장자리에 나오는 페이지, 그리고 현재 페이지 양옆으로 나오는 페이지를 설정하는 값이다. -->
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            <!-- 현재 페이지에 대한 모습을 바꿔주는 코드 -->
            {% if posts.page == page_num %}
                <a class = 'btn btn-info mb-4' href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class = 'btn btn-outline-info mb-4' href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>        
            {% endif %}
        {% else %}
        {% endif %}
    {% endfor %}
    <!-- 위의 내용은 파이썬의 for 문법을 활용할 수 있도록 하는 방식이다. -->
    <!-- 실제로 {} 내부의 내용은 전달된 소스코드에서 확인할 수 없다. -->
{% endblock content %}
<!-- 위의 내용은 extends 된 html에서 content에 해당하는 위치에 해당 내용을 대체한다는 의미이다. -->

flask_blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>
            WTD - {{ title }}
        </title>
    {% else %}
        <title>
            WTD
        </title>
    {% endif %}
    <!-- 위의 내용은 파이썬의 if 문법을 활용할 수 있도록 하는 방식이다. -->
    <!-- 실제로 {} 내부의 내용은 전달된 소스코드에서 확인할 수 없다. -->
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post')}}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class='alert alert-{{ category }}'>
                            {{message}}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- 꾸미는 서식에 대한 부분은 어떤 변수에 저장된 내용인지에 따라서 달라진다. -->
</body>
</html>

flask_blog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class='content-secion'>
        <form method='POST' action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Log In</legend>
                <!-- form 에서 가져올 내용을 하나씩 정리하는 부분 -->
                <!-- 라벨과 forms.py의 변수명(Stringfield 내부의 스트링이 아니다.)이 모두 일치해야 한다. -->
                <!-- 불러온 데이터에 대해서 class 지정을 다음과 같이 설정해준다.-->
                <div class='form-group'>
                    {{ form.email.label(class='form-control-label') }}
                    <!-- form.username.errors에는 이미 에러에 해당하는 문구가 저장되어 있다. -->
                    <!-- 클래스명을 다음과 같이 설정하는 이유가 있다. -->
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-group'>
                    {{ form.password.label(class='form-control-label') }}
                    {% if form.password.errors %}
                        {{ form.password(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
                <div class='form-check'>
                    {{ form.remember(class='form-check-input')}}
                    {{ form.remember.label(class='form-check-label')}}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
            <small class='text-muted ml-2'>
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class='border-top pt-3'>
        <!-- small은 글씨를 작게 만드는 헤더다. -->
        <small class='text-muted'>
            <!-- href를 통해 post 명령을 서버에 보낸다. -->
            Need An Account? <a class='ml-2' href="{{ url_for('register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <!-- home에 있던 for문을 삭제했으므로 게시글 1개만 보여준다. -->
    <article class="media content-section">
        <img class='rounded-circle article-img' src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class='btn btn-secondary btn-sm mt-1 mb-1' href="{{ url_for('posts.update_post',post_id=post.id) }}">Update</a>
                    <button type='button' class=btn btn-danger btn-sm m-1 data-toggle='modal' data-target='#deleteModal'>Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flask_blog/templates/reset_request.html
{% extends 'layout.html' %}
{% block content %}
    <div class='content-secion'>
        <form method='POST' action="">
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <legend class='border-bottom mb-4'>Reset Password</legend>
                <!-- form 에서 가져올 내용을 하나씩 정리하는 부분 -->
                <!-- 라벨과 forms.py의 변수명(Stringfield 내부의 스트링이 아니다.)이 모두 일치해야 한다. -->
                <!-- 불러온 데이터에 대해서 class 지정을 다음과 같이 설정해준다.-->
                <div class='form-group'>
                    {{ form.email.label(class='form-control-label') }}
                    <!-- form.username.errors에는 이미 에러에 해당하는 문구가 저장되어 있다. -->
                    <!-- 클래스명을 다음과 같이 설정하는 이유가 있다. -->
                    {% if form.email.errors %}
                        {{ form.email(class='form-control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class='form-control form-control-lg') }}
                    {% endif %}
                </div>
            </fieldset>
            <div class='form-group'>
                {{ form.submit(class='btn btn-outline-info') }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends 'layout.html' %}
<!-- 위의 내용은 layout.html에 대한 내용을 가져온다는 의미이다. -->
{% block content %}
    <h1 class='mb-3'>Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class='rounded-circle article-img' src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                <!-- author의 내용을 보두 부르는 것 -> username만 부르는 것 -->
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                <!-- 현재시각 초의 소숫자리까지 출력 -> 년월일까지만 부르는 것 -->
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    <!-- 페이지 넘버를 부여하는 html 코드 -->
    {% endfor %}
    <!-- 아래 내용은 가장자리에 나오는 페이지, 그리고 현재 페이지 양옆으로 나오는 페이지를 설정하는 값이다. -->
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            <!-- 현재 페이지에 대한 모습을 바꿔주는 코드 -->
            {% if posts.page == page_num %}
                <a class = 'btn btn-info mb-4' href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class = 'btn btn-outline-info mb-4' href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>        
            {% endif %}
        {% else %}
        {% endif %}
    {% endfor %}
    <!-- 위의 내용은 파이썬의 for 문법을 활용할 수 있도록 하는 방식이다. -->
    <!-- 실제로 {} 내부의 내용은 전달된 소스코드에서 확인할 수 없다. -->
{% endblock content %}
<!-- 위의 내용은 extends 된 html에서 content에 해당하는 위치에 해당 내용을 대체한다는 의미이다. -->